#!/bin/bash
#Выводит на экран три наиболее часто встречающихся слова из man по команде bash длиной не менее четырех символов.
man bash | grep -o "[[:alnum:]]\{4,\}" | uniq -c | sort -nr | head -n 3 | awk -F [[:space:]] '{printf("%s\n", $2)}'
