#!/bin/bash
#Выводит в файл ex4.log для каждого процесса разность резидентной и разделяемой части памяти процесса (в страницах). Данные отсортированы по убыванию разности
ps -A -o pid | tail -n +2 | awk '{ fileTMP="/proc/"$1"/statm"; getline f<fileTMP; close (file); split(f, obj); print($1, ":", obj[2]-obj[3]) }' | sort -r -n -t ":" -k2 > ex4.log
