#!/bin/bash
#В полученном на предыдущем шаге файле после каждой группы записей с одинаковым идентификатором родительского процесса вставляется строку вида Average_Sleeping_Children_of_ParentID=N is M, где N = PPID, а M – среднее, посчитанное из se.avg.runnable_avg для данного процесса.
previousPpid=-1 
countDev=0
sum=0
strNum=0
while read line
do
	ppid=$(echo $line | cut -d ":" -f 2 | grep -E -s -o "[0-9]+")
	avg_at=$(echo $line | cut -d ":" -f 3| grep -E -s -o "[0-9]+")
	
	if [[ ppid -ne previousPpid && previousPpid -ne -1 ]]
	then
		echo "Average_Sleeping_Children_of_ParentID=$previousPpid is  $(echo "scale=2; $sum / $countDev" | bc -l)" >> ex6.tmp
		countDev=0
        	sum=0      	
	fi
	echo $line >> ex6.tmp
	sum=$(echo "scale=2; $sum + $avg_at" | bc -l)
    	previousPpid=$ppid
    	((countDev++))
    	((strNum++))
done < ex5.log
echo "Average_Sleeping_Children_of_ParentID=$previousPpid is  $(echo "scale=2; $sum / $countDev" | bc -l)" >> ex6.tmp
cp ex6.tmp ex5.log
rm ex6.tmp
